licenta/licenta/urls.py
from os import name
from application import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views
from users.views import PasswordsChangeView

handler404 = 'application.views.not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/<username>/', user_views.profile, name='profile'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('application.urls')),

    path("password_reset/", user_views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"), name='password_reset_complete'),

    path('password_change/', PasswordsChangeView.as_view(template_name='password/password_change.html'), name='password_change'),
    path('password_change/done/', user_views.password_change_done, name="password_change_done"),
    
    path('login/', include('allauth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('face_login/', user_views.face_login, name='face_login'),

    path("camera_calibration/",user_views.camera_calibration,name='camera_calibration'),
    path("stereo_calibration/",user_views.stereo_calibration,name='stereo_calibration'),

    path("camera_calibration/delete_camera_config/",user_views.delete_camera_config,name='delete_camera_config'),
    path("stereo_calibration/delete_stereo_config/",user_views.delete_stereo_config,name='delete_stereo_config'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

licenta/users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    
    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        ##TODO resize photo
        # img = ResizedImageField(size=[500, 300], upload_to=self.image.path, blank=True, null=True)

        # if img.height > 500 or img.width > 500:
        #     output_size = (500, 500)
        #     img.thumbnail(output_size)
        #     img.save(self.image.path)

class CameraParameters(models.Model): 
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default='')
    K = models.BinaryField()
    dist = models.BinaryField()
    # rvecs = models.CharField(max_length=200,default='')
    # tvecs = models.CharField(max_length=200,default='')
    focal_length = models.FloatField()

    class Meta: 
        constraints = [models.UniqueConstraint(fields = ['user', 'name'], name = 'unique_constraint')]

    def __str__(self):
        if "predefined" in self.name.lower():
            return self.name
        else:
            return f'{self.name} Configuration'

class StereoCameraParameters(models.Model): 
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=200, default='')
    K1 = models.BinaryField()
    D1 = models.BinaryField()
    K2 = models.BinaryField()
    D2 = models.BinaryField()
    R = models.BinaryField()
    T = models.BinaryField()
    E = models.BinaryField()
    F = models.BinaryField()
    R1 = models.BinaryField()
    P1 = models.BinaryField()
    R2 = models.BinaryField()
    P2 = models.BinaryField()
    Q = models.BinaryField()
    focal_length = models.FloatField()

    class Meta: 
        constraints = [models.UniqueConstraint(fields = ['user', 'name'], name = 'unique_constraint_stereo')]

    def __str__(self):
        if "predefined" in self.name.lower():
            return self.name
        else:
            return f'{self.name} Stereo Configuration'


class ChessboardImage(models.Model):
    image = models.ImageField(default='',upload_to='chessboard_images')

licenta/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, CameraParameters


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.EmailField(widget=forms.TextInput(
        attrs={'class': 'form-control',
                'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password'}
))

class FaceLoginForm(forms.Form):
    username = forms.CharField(label='Username')


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name','email', 'password1', 'password2']
    

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username','email' ]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class ImageUploadForm(forms.Form):
    title = forms.CharField(label="Title")
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


class StereoImageUploadForm(forms.Form): ##TODO filter comboboxes
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'placeholder': 'New configuration'}))
    images_left = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    images_right = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    left_camera_config = forms.ModelChoiceField(label='',queryset=CameraParameters.objects.all(), empty_label='Select Left Camera Configuration*', widget=forms.Select(attrs={'class':'form-select'}))
    right_camera_config = forms.ModelChoiceField(label='',queryset=CameraParameters.objects.all(), empty_label='Select Right Camera Configuration*', widget=forms.Select(attrs={'class':'form-select'}))

    def __init__(self,user, *args, **kwargs):
        super(StereoImageUploadForm, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields['left_camera_config'].queryset = CameraParameters.objects.filter(user=user)
            self.fields['right_camera_config'].queryset = CameraParameters.objects.filter(user=user)







    

licenta/users/views.py
import base64
import json
import os
import pickle

import cv2
import face_recognition
import numpy as np
import PIL.ExifTags
import PIL.Image
from cv2 import CAP_PROP_FRAME_WIDTH
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordChangeView
from django.core.mail import BadHeaderError, send_mail
from django.http import (FileResponse, Http404, HttpResponse, JsonResponse,
                         StreamingHttpResponse)
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from .forms import (FaceLoginForm, ImageUploadForm, ProfileUpdateForm,
                    StereoImageUploadForm, UserRegisterForm, UserUpdateForm)
from .models import (CameraParameters, ChessboardImage, StereoCameraParameters,
                     User)


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    succes_url = reverse_lazy('password_success')


def password_reset_request(request):
    if request.method == "POST":
        
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():

            data = password_reset_form.cleaned_data['email']
            
            if User.objects.filter(email=data).exists():
                user = User.objects.get(email=data) #unique email for user
                
                subject = "Password Reset Requested"
                email_template_name = "password/password_reset_email.txt"

                content = {
                "email":user.email,
                'domain':'127.0.0.1:8000',
                'site_name': 'Rekon',
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "user": user,
                'token': default_token_generator.make_token(user),
                'protocol': 'http',
                }

                email = render_to_string(email_template_name, content)

                try:
                    send_mail(subject, email, settings.EMAIL_HOST_USER , [user.email], fail_silently=False)
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')

                return redirect ("/password_reset/done/")
                
            else:
                messages.warning(request, f"There is no account with the email you provided. Please try again.")
                return redirect('password_reset')
                

    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/password_reset.html", context={"password_reset_form":password_reset_form})


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)

        email = form['email'].value()
        username = form['username'].value()

        if User.objects.filter(username=username).exists():
            messages.warning(request, f"There is already an account with the username you provided.")
            return redirect('register')

        if User.objects.filter(email=email).exists():
            messages.warning(request, f"There is already an account with the email you provided.")
            return redirect('register')

        if form.is_valid():

            form.save() 
            messages.success(request, f'Your account has been created! You are now able to log in.')
            return redirect('login')
    else:
        form = UserRegisterForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)


def face_login(request): ##TODO check error handling here
    if request.method == 'POST':
        form = FaceLoginForm(request.POST)
        username=form['username'].value()

        #get the user with the unique username
        if not(User.objects.filter(username=username).exists()):
            messages.warning(request, f"There is no account with the username you provided.")
            return redirect('face_login')

        user=User.objects.get(username=username) #unique username
        #take photo 
        try:
            cam = cv2.VideoCapture(0) 
        except:
            messages.warning(request,f"There was an error while taking your photo. Make sure that your camera isn't already in use or shut.")
            return redirect('face_login')

        retval, img = cam.read()
        if retval:   #check if the reading was successful
            
            #get user's profile picture path
            profile=user.profile
            # print(type(profile.image))
            profile_image_path=profile.image.path
            # print(profile_image_path)

            #load the profile picture from specific location and encode
            profile_image = face_recognition.load_image_file(profile_image_path)

            try: 
                profile_face_encoding = face_recognition.face_encodings(profile_image)[0]

                #convert the webcam photo to rgb 
                img_rgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

                #locate face in the webcam photo and encode
                face_locations = face_recognition.face_locations(img_rgb)
                face_encodings = face_recognition.face_encodings(img_rgb, face_locations)

                #compare the two images/faces
                
                check=face_recognition.compare_faces(profile_face_encoding, face_encodings)
            except:
                messages.info(request, f"Couldn't identify a face in one of the photos. Please try again and make sure that your face is showing in your profile picture.")
                return redirect('face_login')

            print(check)

            if check[0]:
                #the user can be authenticated
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                messages.success(request, f'You have been successfully authenticated! ')
                return redirect('home')
                
            else:
                messages.warning(request, f"We couldn't verify your identity. Authentication failed.")
                return redirect('face_login')
                
        else:
            messages.warning(request,f"There was an error while taking your photo. Make sure that your camera isn't already in use or shut.")
            return redirect('face_login')
        
    else:
        form = FaceLoginForm()
        context = {'form': form}
        return render(request, 'users/face_login.html', context)


@login_required
def profile(request, username): ##TODO
    if (User.objects.filter(username = username).exists()):
        user = User.objects.filter(username = username)[0] #unique id 

        if (user == request.user): #render editable profile page 
            pass
        else: ##render display only profile page
            pass

        if request.method == 'POST':
            
            u_form = UserUpdateForm(request.POST, instance=user)
            p_form = ProfileUpdateForm(request.POST,
                                    request.FILES,
                                    instance=user.profile)
            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                messages.success(request, f'Your account has been updated!')
                return redirect('profile')

        else:
            u_form = UserUpdateForm(instance=user)
            p_form = ProfileUpdateForm(instance=user.profile)

        context = {
            'user': user,
            'u_form': u_form,
            'p_form': p_form
        }

        return render(request, 'users/profile.html', context)
    else:
        return render(request, "application/404.html")


@login_required
def password_change_done(request):
    return render(request, 'password/password_change_done.html',{})


CHESSBOARD_SIZE = (8,5)
COUNT_IMAGES_CHESSBOARD = 10

def list2string(array):
    listToStr = ' '.join([str(elem) for elem in array])

    return listToStr

@login_required
def camera_calibration(request): ##TODO error handling
    
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)

        #check if name/title already exists
        title = form['title'].value()
        if CameraParameters.objects.filter(name=title, user=request.user).exists():
            messages.warning(request, f"There is already a configuration with the title you provided. Retry")
            return redirect('camera_calibration')


        if form.is_valid():
            
            chessboardCaptured = 0

            #Define arrays to save detected points
            obj_points = [] #3D points in real world space 
            img_points = [] #3D points in image plane
            #Prepare grid and points to display
            objp = np.zeros((np.prod(CHESSBOARD_SIZE),3),dtype=np.float32)
            objp[:,:2] = np.mgrid[0:CHESSBOARD_SIZE[0], 0:CHESSBOARD_SIZE[1]].T.reshape(-1,2) * 0.03

            #termination criteria for subpixel accuracy
            criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

            focal_length = None
            First = True

            for img in request.FILES.getlist('images'):
                Image = ChessboardImage.objects.create(image=img)
                
                #verify the file extension - must be png or jpg
                extension = Image.image.path[-3:]
                if extension.lower() != 'png' and extension.lower() != 'jpg':

licenta/users/templates/users/camera_calibration.html
{% extends "application/base.html" %}
{% load crispy_forms_tags %}

{% block title %} <title> Camera Calibration </title> {% endblock title %}


{% block content %}

    {% if user.is_authenticated %}

        <style>
            #instructions {
                color: black
            }

            #chess-a {
                color: #1e5aba
            }

            @media (min-width: 1024px) {
                .lg\:w-1\/5 {
                    width: 33%;
                }
            }
        </style>

        <br>
        <br>
        <div class="content-section" id="instructions"> In order to proper calibrate your camera, you must upload at least 15
            photos of the
            <a class="content-section" id="chess-a" href="http://boofcv.org/images/c/cc/Calibration_A4_chessboard_9x6.png"
                download>chessboard pattern.
            </a>
            Please make sure that the pictures you take have good illumination
            and that you capture the chessboard from different angles. It is highly recommended to use a clean background, as it
            improves the algorithm's speed.
        </div>
        <hr>
        <br>
        <br>

        <form method="POST" id="uploadimgform" enctype="multipart/form-data">
            {% csrf_token %}


            <div id="div_id_title" class="form-group"> <label for="id_title" class=" requiredField">
                    Title<span class="asteriskField ">*</span> </label>
                <div class="pad"> <input type="text" name="title" placeholder="New configuration"
                        class="textinput textInput form-control marg" required id="id_title"> </div>
            </div>
            <div id="div_id_images" class="form-group"> <label for="id_images" class=" requiredField">
                    Images<span class="asteriskField ">*</span> </label>
                <div class="pad"> <input type="file" name="images" multiple class="clearablefileinput form-control-file marg"
                        required id="id_images" accept='image/*'> </div>
            </div>

            <button class='btn btn-outline-info height marg' type="submit">Upload</button>
        </form>

        <small class="text-muted">The fields marked with * are mandatory </small>
        <br>
        <br>

        <legend class="border-bottom mb-4">My configurations</legend>
        <!-- display configurations  -->
        {% if CameraParamObjs %}
            {% for camparamobj in CameraParamObjs %}

                <div class="text-lg">{{camparamobj.name}}</div>
                <div class="min-w-screen bg-gray-100 flex items-center justify-center" style="background-color: white;">
                    <div class="max-w-7xl w-full mx-auto py-6 sm:px-6 lg:px-8">
                        <div class="flex flex-col lg:flex-row w-full lg:space-x-2 space-y-2 lg:space-y-0 mb-2 lg:mb-4">

                            <div class="w-full lg:w-1/5">
                                <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-purple-400"
                                    style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                                    <div class="flex items-center">
                                        <div class="flex flex-col justify-center">
                                            <div class="text-lg">Camera matrix</div>
                                            <div class="text-sm text-gray-400">{{ camparamobj.K }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="w-full lg:w-1/5">
                                <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-blue-400"
                                    style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                                    <div class="flex items-center">
                                        <div class="flex flex-col justify-center">
                                            <div class="text-lg">Distortion coefficients</div>
                                            <div class="text-sm text-gray-400">{{ camparamobj.dist }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="w-full lg:w-1/5">
                                <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-yellow-400"
                                    style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                                    <div class="flex items-center">
                                        <div class="flex flex-col justify-center">
                                            <div class="text-lg">Focal Length (mm)</div>
                                            <div class="text-sm text-gray-400">{{ camparamobj.focal_length }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
            <br>
            <!-- delete configurations  -->
            <legend class="border-bottom mb-4">Delete configurations</legend>
            <div class="content-section"> Please select the title for the configuration you want to delete. </div>
            <br>

            <form method="POST" action="{% url 'delete_camera_config' %}">
                {% csrf_token %}

                <div style="display: inline-flex; margin-bottom: 10px;">
                    <select class="form-select" aria-label="Default select example" name="select" required>

                        <option value="" disabled selected>Open the select menu</option>
                        {% for camparamobj in CameraParamObjs %}
                            <option value="{{camparamobj.name}}">{{camparamobj.name}}</option>
                        {% endfor %}
                    </select>

                    <button class='btn btn-outline-info height marg' type="submit">Delete</button>
                </div>
            </form>
            <hr>

        {% else %}
            <div class="content-section"> No configurations added. </div>

        {% endif %}

    {% else %}

        <div class="content-section">
            You need to be logged in in order to access this page.

        </div>
        <hr>
        <div class="border-top pt-3">
            <small class="text-muted">

                <a class="ml-2" href="{% url 'login' %}">Log in</a>
            </small>
        </div>

    {% endif %}


{% endblock content %}

licenta/users/templates/users/face_login.html
{% extends "application/base.html" %}
{% load crispy_forms_tags %}

{% block title %} <title> Login </title> {% endblock title %}

{% block content %}

    {% if user.is_authenticated %}

        <div class="content-section">
            You are already logged in.

        </div>
        <hr>

        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'logout' %}">Log out</a>
            </small>
        </div>

    {% else %}

        <br>
        <div class="flex min-h-screen bg-white" style="min-height: 90vh; justify-content: center;">

            <div class="w-1/2 bg-cover md:block hidden"
                style="margin-right: 20px; box-sizing:border-box; background-image:  url(https://images.unsplash.com/photo-1515462277126-2dd0c162007a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=635&q=80)">
            </div>


            <div class="content-section">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Log In</legend>
                        {{ form|crispy }}
                        <small class="text-muted">The fields marked with * are mandatory </small>
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Login using Face ID</button>
                    </div>
                </form>
            </div>
        </div>

    {% endif %}

{% endblock content %}

licenta/users/templates/users/logout.html
{% extends "application/base.html" %}
{% block title %} <title> Logout </title> {% endblock title %}

{% block content %}

    <br>
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{% url 'login' %}">Log in again</a>
        </small>
    </div>

{% endblock content %}

licenta/users/templates/users/profile.html
{% extends "application/base.html" %}
{% load crispy_forms_tags %}

{% block title %} <title> Profile | {{user.username}} </title> {% endblock title %}

{% block content %}


    <style>
        #override {
            min-height: 80vh;
            display: flex;
            justify-content: space-evenly;
        }

        #btnopt {
            display: flex;
            justify-content: space-evenly;
        }

        .material-card {
            font-family: 'Roboto', sans-serif;
            background-color: #FFF;
            box-shadow: 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, .12);
        }

        @media screen and (min-width: 769px) {
            #override1 {
                margin-right: 50px;
            }
        }

        @media screen and (max-width: 360px) {

            #btnopt {
                display: grid;
            }

            .marg {
                margin-bottom: 10px;
            }


        }


        @media screen and (max-width: 768px) {

            #override {
                display: block;

            }

            .material-card {
                margin: auto;
            }


        }
    </style>

    <br>
    <div id="override">

        <div class="max-w-sm rounded material-card bg-white" style="text-align: center; height: 50%; ">
            <img class="w-full rounded-t" src="{{ user.profile.image.url }}">
            <div class="px-6 py-4">
                <div class="font-bold text-xl tracking-wide">{{ user.username }}</div>
                <div class="text-gray-500 text-sm mb-3">{{ user.email }}</div>
            </div>
        </div>


        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>

                <div id="first_name" class="form-group"> <label for="first_name" class=" requiredField">
                        First Name</label>
                    <div class=""> <input type="text" name="first_name" value="{{user.first_name}}" class="form-control"
                            required id="first_name"> </div>
                </div>
                <div id="last_name" class="form-group"> <label for="last_name" class=" requiredField">
                        Last Name</label>
                    <div class=""> <input type="text" name="last_name" value="{{user.last_name}}" class="form-control"
                            required id="last_name"> </div>
                </div>

                <div id="div_id_username" class="form-group"> <label for="id_username" class=" requiredField">
                        Username<span class="asteriskField">*</span> </label>
                    <div class=""> <input type="text" name="username" value="{{user.username}}" maxlength="150"
                            class="textinput textInput form-control" required id="id_username"> <small id="hint_id_username"
                            class="form-text text-muted">150 characters or fewer. Letters, digits and @/./+/-/_
                            only.</small> </div>
                </div>
                <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
                        Email<span class="asteriskField">*</span> </label>
                    <div class=""> <input type="email" name="email" value="{{user.email}}" class="emailinput form-control"
                            required id="id_email"> </div>
                </div>



                <div id="div_id_image" class="form-group"> <label for="id_image" class=" requiredField">
                        Image<span class="asteriskField">*</span> </label>
                    <div class="">

                        <input type="file" name="image" accept="image/*" class="clearablefileinput form-control-file"
                            id="id_image">
                    </div>
                </div>

            <small class="text-muted">The fields marked with * are mandatory </small>
            </fieldset>


            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
                <a href="/password_change" class="btn btn-outline-info">Change password</a>

            </div>


            <hr>
            <br>

            <div id="btnopt">
                <a href="/camera_calibration" class="btn btn-primary marg">Single calibration</a>
                <a href="/stereo_calibration" class="btn btn-primary marg">Stereo calibration</a>
            </div>

        </form>
    </div>


{% endblock content %}